### ISSUE TITLE
error handling 

### ISSUE THREAD

**Issue by bkh751** [smok95/gokiwoom#1]
안녕하세요 kiwoom api 를 wrapper 로 잘 작성해주셔서 감사합니다. 

에러핸들링이 아직은 들어가있지않아 보입니다. 개선사항으로 제가 진행 해보고싶은데 괜찮으신가요?

**Comment by smok95** [comment]
안녕하세요! 네 그럼요 괜찮습니다!

**Comment by bkh751** [comment]
나중에 진행할때 다시 오픈하겠습니다

**Comment by smok95** [comment]
> 나중에 진행할때 다시 오픈하겠습니다

네!~
